-- Add medical condition columns to patients table
-- Used by Notes tab checkboxes and Profile tab display (configurable in Settings > Patient)

ALTER TABLE patients
  ADD COLUMN IF NOT EXISTS is_diabetic BOOLEAN DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS is_hypertensive BOOLEAN DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS has_pancreatitis BOOLEAN DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS has_gerd BOOLEAN DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS has_gastritis BOOLEAN DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS has_hepatic BOOLEAN DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS has_anaemia BOOLEAN DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS has_bronchial_asthma BOOLEAN DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS has_rheumatoid BOOLEAN DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS has_ihd BOOLEAN DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS has_heart_failure BOOLEAN DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS is_pregnant BOOLEAN DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS is_breastfeeding BOOLEAN DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS glp1a_previous_exposure BOOLEAN DEFAULT NULL;
